[package]
name = "toy-helix"
version = "0.1.0"
edition = "2021"

[features]
defualt = []


[dependencies]
anyhow = "1.0.68"
serde = { version = "1.0", features = ["derive"] , optional = true }
bitflags = "1.3.2"
